# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'functionsettings.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settings(object):
    def setupUi(self, settings):
        settings.setObjectName("settings")
        settings.resize(445, 533)
        settings.setMinimumSize(QtCore.QSize(445, 533))
        settings.setMaximumSize(QtCore.QSize(445, 533))
        settings.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(settings)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 9, 101, 16))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 30, 118, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.duration_T = QtWidgets.QLabel(self.centralwidget)
        self.duration_T.setGeometry(QtCore.QRect(10, 40, 91, 16))
        self.duration_T.setObjectName("duration_T")
        self.fps_T = QtWidgets.QLabel(self.centralwidget)
        self.fps_T.setGeometry(QtCore.QRect(10, 100, 61, 16))
        self.fps_T.setObjectName("fps_T")
        self.gif_name_T = QtWidgets.QLabel(self.centralwidget)
        self.gif_name_T.setGeometry(QtCore.QRect(160, 100, 71, 16))
        self.gif_name_T.setObjectName("gif_name_T")
        self.duration = QtWidgets.QLineEdit(self.centralwidget)
        self.duration.setGeometry(QtCore.QRect(10, 60, 113, 20))
        self.duration.setObjectName("duration")
        self.fps = QtWidgets.QLineEdit(self.centralwidget)
        self.fps.setGeometry(QtCore.QRect(10, 120, 113, 20))
        self.fps.setObjectName("fps")
        self.gif_name = QtWidgets.QLineEdit(self.centralwidget)
        self.gif_name.setGeometry(QtCore.QRect(160, 120, 113, 20))
        self.gif_name.setObjectName("gif_name")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(160, 10, 101, 16))
        self.label_5.setObjectName("label_5")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(160, 30, 118, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.coo_range_T = QtWidgets.QLabel(self.centralwidget)
        self.coo_range_T.setGeometry(QtCore.QRect(310, 100, 121, 16))
        self.coo_range_T.setObjectName("coo_range_T")
        self.coo_range = QtWidgets.QLineEdit(self.centralwidget)
        self.coo_range.setGeometry(QtCore.QRect(310, 120, 113, 20))
        self.coo_range.setObjectName("coo_range")
        self.pic_size_T = QtWidgets.QLabel(self.centralwidget)
        self.pic_size_T.setGeometry(QtCore.QRect(160, 40, 91, 16))
        self.pic_size_T.setObjectName("pic_size_T")
        self.pic_size = QtWidgets.QLineEdit(self.centralwidget)
        self.pic_size.setGeometry(QtCore.QRect(160, 60, 113, 20))
        self.pic_size.setObjectName("pic_size")
        self.m_range_T = QtWidgets.QLabel(self.centralwidget)
        self.m_range_T.setGeometry(QtCore.QRect(310, 160, 131, 16))
        self.m_range_T.setObjectName("m_range_T")
        self.m_range = QtWidgets.QLineEdit(self.centralwidget)
        self.m_range.setGeometry(QtCore.QRect(310, 180, 113, 20))
        self.m_range.setObjectName("m_range")
        self.keep_track = QtWidgets.QCheckBox(self.centralwidget)
        self.keep_track.setGeometry(QtCore.QRect(10, 220, 321, 16))
        self.keep_track.setObjectName("keep_track")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 10, 101, 16))
        self.label_2.setObjectName("label_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(310, 30, 118, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 40, 111, 16))
        self.label_3.setObjectName("label_3")
        self.precision = QtWidgets.QLineEdit(self.centralwidget)
        self.precision.setGeometry(QtCore.QRect(310, 60, 113, 20))
        self.precision.setObjectName("precision")
        self.x_fm = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.x_fm.setGeometry(QtCore.QRect(10, 270, 411, 71))
        self.x_fm.setObjectName("x_fm")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 250, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 350, 61, 16))
        self.label_6.setObjectName("label_6")
        self.y_gm = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.y_gm.setGeometry(QtCore.QRect(10, 370, 411, 71))
        self.y_gm.setObjectName("y_gm")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(324, 450, 101, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(160, 160, 91, 16))
        self.label_7.setObjectName("label_7")
        self.storage_path = QtWidgets.QLineEdit(self.centralwidget)
        self.storage_path.setGeometry(QtCore.QRect(160, 180, 113, 20))
        self.storage_path.setMouseTracking(False)
        self.storage_path.setObjectName("storage_path")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 160, 111, 16))
        self.label_8.setObjectName("label_8")
        self.bk_color = QtWidgets.QLineEdit(self.centralwidget)
        self.bk_color.setGeometry(QtCore.QRect(10, 180, 113, 20))
        self.bk_color.setObjectName("bk_color")
        settings.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(settings)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 445, 23))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        settings.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(settings)
        self.statusbar.setObjectName("statusbar")
        settings.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(settings)
        self.actionopen.setObjectName("actionopen")
        self.actionAbout = QtWidgets.QAction(settings)
        self.actionAbout.setObjectName("actionAbout")
        self.menufile.addAction(self.actionopen)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(settings)
        QtCore.QMetaObject.connectSlotsByName(settings)

    def retranslateUi(self, settings):
        _translate = QtCore.QCoreApplication.translate
        settings.setWindowTitle(_translate("settings", "settings"))
        self.label.setText(_translate("settings", "gif settings"))
        self.duration_T.setText(_translate("settings", "duration (s) *"))
        self.fps_T.setText(_translate("settings", "fps *"))
        self.gif_name_T.setText(_translate("settings", "gif name *"))
        self.label_5.setText(_translate("settings", "picture settings"))
        self.coo_range_T.setText(_translate("settings", "range of coordinates"))
        self.pic_size_T.setText(_translate("settings", "size of picture"))
        self.m_range_T.setText(_translate("settings", "range of parameter(m)"))
        self.keep_track.setText(_translate("settings", "Check if you want to keep track of the function(s)"))
        self.label_2.setText(_translate("settings", "function settings"))
        self.label_3.setText(_translate("settings", "function precision"))
        self.label_4.setText(_translate("settings", "x=f(m) *"))
        self.label_6.setText(_translate("settings", "y=g(m) *"))
        self.pushButton.setText(_translate("settings", "make the gif"))
        self.label_7.setText(_translate("settings", "storage path *"))
        self.label_8.setText(_translate("settings", "background color *"))
        self.menufile.setTitle(_translate("settings", "file"))
        self.menuAbout.setTitle(_translate("settings", "about"))
        self.actionopen.setText(_translate("settings", "open..."))
        self.actionAbout.setText(_translate("settings", "About"))
